{"name": "test_add_user[base_info0-testcase0]", "status": "broken", "statusDetails": {"message": "SystemExit: None", "trace": "@pytest.fixture(scope='session', autouse=True)\n    @allure.story(\"登录\")\n    def system_login():\n        try:\n            api_info = get_testcase_yaml('./data/loginName.yaml')\n>           RequestBase().specification_yaml(api_info[0][0], api_info[0][1])\n\ntestcase\\conftest.py:30: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nbase\\apiutil.py:118: in specification_yaml\n    raise e\nbase\\apiutil.py:115: in specification_yaml\n    raise e\nbase\\apiutil.py:109: in specification_yaml\n    self.asserts.assert_result(validation, res_json, status_code)\ncommon\\assertions.py:197: in assert_result\n    raise exceptions\ncommon\\assertions.py:181: in assert_result\n    flag = self.equal_assert(value, response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pythonproject.common.assertions.Assertions object at 0x0000023CBC224640>\nexpected_results = {'msg': '登录成功'}\nactual_results = {'error_code': None, 'msg': '登录成功', 'msg_code': 200, 'orgId': '6140913758128971280', ...}\nstatuc_code = None\n\n    def equal_assert(self, expected_results, actual_results, statuc_code=None):\n        \"\"\"\n        相等断言模式\n        :param expected_results: 预期结果，yaml文件validation值\n        :param actual_results: 接口实际响应结果\n        :return:\n        \"\"\"\n        flag = 0\n        if isinstance(actual_results, dict) and isinstance(expected_results, dict):\n            # 找出实际结果与预期结果共同的key\n>           common_keys = list(list(expected_results.keys()) & list(actual_results.keys()))[0]\nE           TypeError: unsupported operand type(s) for &: 'list' and 'list'\n\ncommon\\assertions.py:65: TypeError\n\nDuring handling of the above exception, another exception occurred:\n\n    @pytest.fixture(scope='session', autouse=True)\n    @allure.story(\"登录\")\n    def system_login():\n        try:\n            api_info = get_testcase_yaml('./data/loginName.yaml')\n            RequestBase().specification_yaml(api_info[0][0], api_info[0][1])\n        except Exception as e:\n            logs.error(f'登录接口出现异常，导致后续接口无法继续运行，请检查程序！，{e}')\n>           exit()\n\ntestcase\\conftest.py:33: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = Use exit() or Ctrl-Z plus Return to exit, code = None\n\n    def __call__(self, code=None):\n        # Shells like IDLE catch the SystemExit, but listen when their\n        # stdin wrapper is closed.\n        try:\n            sys.stdin.close()\n        except:\n            pass\n>       raise SystemExit(code)\nE       SystemExit: None\n\nC:\\Users\\86135\\AppData\\Local\\Programs\\Python\\Python39\\lib\\_sitebuiltins.py:26: SystemExit"}, "attachments": [{"name": "log", "source": "da697e66-6f2d-46fe-99f3-92ee343ea57f-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "base_info", "value": "{'api_name': '新增用户', 'url': '/dar/user/addUser', 'method': 'POST', 'header': {'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'}}"}, {"name": "testcase", "value": "{'case_name': '正常新增用户', 'data': {'username': 'testadduser', 'password': 'tset6789890', 'role_id': 123456789, 'dates': '2023-12-31', 'phone': 13800000000, 'token': '${get_extract_data(token)}'}, 'validation': [{'contains': {'status_code': 200}}, {'contains': {'msg': '新增成功'}}]}"}], "start": 1739351153978, "stop": 1739351153978, "uuid": "b9b82c71-a05b-4df9-972a-d8b684b7be02", "historyId": "5cb57ad107f9f0b7c3f46855cbf2bb85", "testCaseId": "37cf0d175a552f57ad9469bc9f0b52e8", "fullName": "testcase.Single interface.test_debug_api.TestUserManager#test_add_user", "labels": [{"name": "story", "value": "C06_新增用户"}, {"name": "feature", "value": "M03_用户管理模块（单接口）"}, {"name": "tag", "value": "run(order=1)"}, {"name": "parentSuite", "value": "testcase.Single interface"}, {"name": "suite", "value": "test_debug_api"}, {"name": "subSuite", "value": "TestUserManager"}, {"name": "host", "value": "Henry"}, {"name": "thread", "value": "25672-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.Single interface.test_debug_api"}]}